FROM ubuntu@sha256:fed6ddb82c61194e1814e93b59cfcb6759e5aa33c4e41bb3782313c2386ed6df

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /workspace

RUN apt-get update

RUN apt-get install -y software-properties-common

RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test
RUN apt-get update

RUN apt-get install -y \
    python3 \
    python3-venv \
    python3-pip

RUN apt-get install -y git vim curl nlohmann-json3-dev

RUN apt-get -y install \
  binutils-arm-none-eabi \
  gcc-arm-none-eabi \
  gcc-11 g++-11 \
  clang clang-format gdb \
  libncurses-dev libsdl2-dev

RUN ln -sf /usr/bin/gcc-11 /usr/bin/gcc || true

CMD ["/bin/bash"]
