#!/bin/bash

set -euo pipefail
pushd fwxvi

TAGS=${TAGS:-}

TAG_LINE=${TAG_LINE:-}
for tag in $TAGS; do
  TAG_LINE+=(-t $tag)
done

docker buildx build \
       --platform linux/arm64,linux/amd64 \
       -f Containerfile \
       -t fwxvi:latest \
       --push \
       $TAG_LINE \
       .

popd
