#!/bin/bash

set -euo pipefail
pushd fwxvi

docker buildx build \
       --platform linux/arm64,linux/amd64 \
       -f Containerfile \
       -t fwxvi:latest \
       --load \
       .


for tag in $TAGS; do
    docker tag fwxvi:latest $tag
    docker push $tag
done

popd
