#!/bin/bash

set -euo pipefail
pushd fwxvi

TAG_LINE=$(echo $TAGS | sed  sed 's/\([^ ]\+\)/-t \1/g')

docker buildx build \
       --platform linux/arm64,linux/amd64 \
       -f Containerfile \
       -t fwxvi:latest \
       --push \
       $TAG_LINE \
       .

popd
