FROM ubuntu@sha256:fed6ddb82c61194e1814e93b59cfcb6759e5aa33c4e41bb3782313c2386ed6df

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update

RUN apt-get install -y software-properties-common

RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test
RUN apt-get update

RUN apt-get -y install \
  binutils-arm-none-eabi \
  gcc-arm-none-eabi \
  gcc-11 g++ \
  clang clang-format gdb \
  libncurses-dev libsdl2-dev

RUN ln -sf /usr/bin/gcc-11 /usr/bin/gcc || true

RUN apt-get install -y \
    python3 \
    python3-venv \
    python3-pip

RUN apt-get install -y  qt6-base-dev qt6-tools-dev-tools qt6-tools-dev

RUN apt-get install -y git vim curl nlohmann-json3-dev

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY ./requirements.txt /tmp/requirements.txt
RUN python3 -m pip install --no-cache-dir -r /tmp/requirements.txt

USER ubuntu
CMD ["/bin/bash"]
