#!/bin/bash

function print_green() {
 local ANSI_GREEN="\033[32m"
 local ANSI_GREEN_END="\033[0m"

 echo -e "${ANSI_GREEN}${1}${ANSI_GREEN_END}"
}

set -euo pipefail

PROJECT=${PROJECT:-}
VERSION=${VERSION:-latest}

print_green "\nBuilding devcontainer image for the ${PROJECT} project.\n"

${PROJECT}/build

echo "Build sucessful!"

TAG="ghcr.io/uw-midsun/devcontainers/${PROJECT}:${VERSION}"

print_green "\nTagging image as ${TAG}.\n"

docker tag $PROJECT:latest $TAG

docker push $TAG $PROJECT:latest
